"""Add incident relationships and timeline support

Revision ID: c17aaf851afe
Revises: 001
Create Date: 2026-05-06 00:42:05.996813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c17aaf851afe'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_relationships',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('source_incident_id', sa.String(length=26), nullable=False),
    sa.Column('target_incident_id', sa.String(length=26), nullable=False),
    sa.Column('relationship_type', sa.Enum('ROOT_CAUSE', 'CASCADED_FROM', 'RELATED_TO', name='relationshiptype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detection_method', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_incident_id'], ['work_items.id'], ),
    sa.ForeignKeyConstraint(['target_incident_id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_relationships_created_at'), 'incident_relationships', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_relationships_source_incident_id'), 'incident_relationships', ['source_incident_id'], unique=False)
    op.create_index(op.f('ix_incident_relationships_target_incident_id'), 'incident_relationships', ['target_incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_items', 'first_signal_id',
               existing_type=sa.String(length=26),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.drop_index(op.f('ix_incident_relationships_target_incident_id'), table_name='incident_relationships')
    op.drop_index(op.f('ix_incident_relationships_source_incident_id'), table_name='incident_relationships')
    op.drop_index(op.f('ix_incident_relationships_created_at'), table_name='incident_relationships')
    op.drop_table('incident_relationships')
    # ### end Alembic commands ###
